- name: "download {{component}} application"
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: "java setup for {{component}}"
  ansible.builtin.import_role:
    name: common
    tasks_from: java

- name: "mysql setup for {{component}}"
  ansible.builtin.import_role:
    name: common
    tasks_from: mysql-setup

- name: "start {{component}} service"
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd